### ISSUE TITLE
Can you clarify results, use at CERN?

### ISSUE THREAD

**Issue by PallHaraldsson** [mmikhasenko/ThreeBodyDecay.jl#20]
Hi,

I noticed your work, and use of Julia at CERN. See edited section with CERN added at Julia's Wikipedia page.

Can you clarify if Julia was instrumental in discovering a new pentaquark, and what possible other uses/discovery with Julia? I don't want Wikipedia to be misleading or overstating Julia's use. Maybe it's still mostly for plotting? But that seems deceiving, since HEP is all about analysis, and plots very important, for analysing data. Julia is (only?) used for analysis, not in any actual instrument (not meaning that the most important work is on that side).

I tried to read your paper, and it references this Julia code, but also C++ code, so C++ could have been more or only important, or (all three C++/Julia/Python) while your other pdf mentions Julia is ready, but unclear if used (much), or by how many.

I'm aware of UpROOT.jl and UnROOT.jl, both I guess helpful, is old ROOT/Python code on the way out?

**Comment by mmikhasenko** [comment]
Hi @PallHaraldsson,

sorry for missing the question earlier. I did not get notification. The Julia is a great tool for data analysis and complex analysis. Admittedly, there is nothing in Julia that you cannot do with C++ or python. However, for my work I use mostly Julia. So, analyses where I am a proponent, in large fraction done in Julia (unfortunately, the citation of Julia is often missing).

Here are some of them:
 - Parameters of a1(1260) (PRD), https://inspirehep.net/literature/1696497
 - a1(1420) as the Triangle singularity (PRL), https://inspirehep.net/literature/1800396
 - Angular analysisi of Omega_c states (PRD Letters), https://inspirehep.net/literature/1879440
 - Study of tetraquark Tcc (NC), https://inspirehep.net/literature/1915358
 - Dalitz Plot Decomposition (PRD), https://inspirehep.net/literature/1758460

The discovery of the first pentaquarks was in 2015, I did not work on it. However, Julia is in integral part of the current studies of these pentaquarks. The paper is likely to be published next year.

**Comment by mmikhasenko** [comment]
> I'm aware of UpROOT.jl and UnROOT.jl, both I guess helpful, is old ROOT/Python code on the way out?

`UpROOT.jl` is a python wrapper. the `UnROOT.jl` is native julia.

**Comment by mmikhasenko** [comment]
Closing for now

feel free to drop me an email, mikhail.mikhasenko@cern.ch
